#ifndef _DRIVE
#define _DRIVE

#include "Control.h"
//----------------- Silniki DC
#define MOT0INA_SET				GPIOA->ODR |= GPIO_ODR_ODR_4
#define MOT0INA_CLR				GPIOA->ODR &= ~GPIO_ODR_ODR_4
#define MOT0INB_SET				GPIOA->ODR |= GPIO_ODR_ODR_5
#define MOT0INB_CLR				GPIOA->ODR &= ~GPIO_ODR_ODR_5
#define MOT0FOR						{MOT0INA_SET; MOT0INB_CLR;}
#define MOT0BACK					{MOT0INA_CLR; MOT0INB_SET;}
#define MOT0STOP					{MOT0INA_CLR; MOT0INB_CLR;}
#define MOT0PWM_REG				TIM9->CCR1

#define MOT1INA_SET				GPIOC->ODR |= GPIO_ODR_ODR_4
#define MOT1INA_CLR				GPIOC->ODR &= ~GPIO_ODR_ODR_4
#define MOT1INB_SET				GPIOC->ODR |= GPIO_ODR_ODR_5
#define MOT1INB_CLR				GPIOC->ODR &= ~GPIO_ODR_ODR_5
#define MOT1FOR						{MOT1INA_SET; MOT1INB_CLR;}
#define MOT1BACK					{MOT1INA_CLR; MOT1INB_SET;}
#define MOT1STOP					{MOT1INA_CLR; MOT1INB_CLR;}
#define MOT1PWM_REG				TIM9->CCR2

#define MOT2INA_SET				GPIOB->ODR |= GPIO_ODR_ODR_0
#define MOT2INA_CLR				GPIOB->ODR &= ~GPIO_ODR_ODR_0
#define MOT2INB_SET				GPIOB->ODR |= GPIO_ODR_ODR_1
#define MOT2INB_CLR				GPIOB->ODR &= ~GPIO_ODR_ODR_1
#define MOT2FOR						{MOT2INA_SET; MOT2INB_CLR;}
#define MOT2BACK					{MOT2INA_CLR; MOT2INB_SET;}
#define MOT2STOP					{MOT2INA_CLR; MOT2INB_CLR;}
#define MOT2PWM_REG				TIM13->CCR1

#define MOT3INA_SET				GPIOB->ODR |= GPIO_ODR_ODR_2
#define MOT3INA_CLR				GPIOB->ODR &= ~GPIO_ODR_ODR_2
#define MOT3INB_SET				GPIOE->ODR |= GPIO_ODR_ODR_7
#define MOT3INB_CLR				GPIOE->ODR &= ~GPIO_ODR_ODR_7
#define MOT3FOR						{MOT3INA_SET; MOT3INB_CLR;}
#define MOT3BACK					{MOT3INA_CLR; MOT3INB_SET;}
#define MOT3STOP					{MOT3INA_CLR; MOT3INB_CLR;}
#define MOT3PWM_REG				TIM14->CCR1

#define MOT4INA_SET				GPIOB->ODR |= GPIO_ODR_ODR_12
#define MOT4INA_CLR				GPIOB->ODR &= ~GPIO_ODR_ODR_12
#define MOT4INB_SET				GPIOB->ODR |= GPIO_ODR_ODR_13
#define MOT4INB_CLR				GPIOB->ODR &= ~GPIO_ODR_ODR_13
#define MOT4FOR						{MOT4INA_SET; MOT4INB_CLR;}
#define MOT4BACK					{MOT4INA_CLR; MOT4INB_SET;}
#define MOT4STOP					{MOT4INA_CLR; MOT4INB_CLR;}
#define MOT4PWM_REG				TIM12->CCR1

//------------------ Serwonapedy modelarskie
#define SERW0PWM_REG			TIM8->CCR1
#define SERW1PWM_REG			TIM8->CCR2
#define SERW2PWM_REG			TIM8->CCR3
#define SERW3PWM_REG			TIM8->CCR4
#define SERW4PWM_REG			TIM1->CCR1
#define SERW5PWM_REG			TIM1->CCR2
#define SERW6PWM_REG			TIM1->CCR3
#define SERW7PWM_REG			TIM1->CCR4


void Drive_Conf(void);


#endif
