#ifndef _ADDDVEICE
#define _ADDDVEICE

#include "Control.h"

#define LED_PORT		GPIOE
#define LED1_PIN		GPIO_ODR_ODR_0
#define LED2_PIN		GPIO_ODR_ODR_1
#define LED3_PIN		GPIO_ODR_ODR_2
#define LED4_PIN		GPIO_ODR_ODR_3
#define LED5_PIN		GPIO_ODR_ODR_4

#define LED1_ON			LED_PORT->ODR |= LED1_PIN;
#define LED1_OFF		LED_PORT->ODR &= ~LED1_PIN;
#define LED1_TOG		LED_PORT->ODR ^= LED1_PIN;
#define LED2_ON			LED_PORT->ODR |= LED2_PIN;
#define LED2_OFF		LED_PORT->ODR &= ~LED2_PIN;
#define LED2_TOG		LED_PORT->ODR ^= LED2_PIN;
#define LED3_ON			LED_PORT->ODR |= LED3_PIN;
#define LED3_OFF		LED_PORT->ODR &= ~LED3_PIN;
#define LED3_TOG		LED_PORT->ODR ^= LED3_PIN;
#define LED4_ON			LED_PORT->ODR |= LED4_PIN;
#define LED4_OFF		LED_PORT->ODR &= ~LED4_PIN;
#define LED4_TOG		LED_PORT->ODR ^= LED4_PIN;
#define LED5_ON			LED_PORT->ODR |= LED5_PIN;
#define LED5_OFF		LED_PORT->ODR &= ~LED5_PIN;
#define LED5_TOG		LED_PORT->ODR ^= LED5_PIN;

#define LEDALL_ON		LED_PORT->ODR |= LED1_PIN | LED2_PIN | LED3_PIN | LED4_PIN | LED5_PIN;
#define LEDALL_OFF	LED_PORT->ODR &= ~LED1_PIN & ~LED2_PIN & ~LED3_PIN & ~LED4_PIN & ~LED5_PIN;
#define LEDALL_TOG	LED1_TOG;LED2_TOG;LED3_TOG;LED4_TOG;LED5_TOG;

#define LASER_ON			GPIOA->ODR |= GPIO_ODR_ODR_11;
#define LASER_OFF			GPIOA->ODR &= ~GPIO_ODR_ODR_11;
#define SOLENOID_ON		GPIOA->ODR |= GPIO_ODR_ODR_12;
#define SOLENOID_OFF	GPIOA->ODR &= ~GPIO_ODR_ODR_12;

void AddDev_Conf(void);

#endif
